### PR TITLE
Add Offline Support

### PR DESCRIPTION
**Pull request by vj-abishek**
#8

### CODE REVIEW

**Comment by vj-abishek** [comment]
@jaideepghosh is this okay?

**Comment by jaideepghosh** [comment]
Hey @vj-abishek 
Great work 🎉 
But `navigator.onLine` will only help us in the case when the page is alrady open. in case of refresh, it will show browser's default offline screen.
For your ref, please find the resources below, and let me know if you need any help.
https://googlechrome.github.io/samples/service-worker/custom-offline-page/
https://developers.google.com/web/fundamentals/codelabs/offline
https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience-c84db889162c

**Comment by vj-abishek** [comment]
@jaideepghosh then okay I will remove it.

**Comment by vj-abishek** [comment]
@jaideepghosh why closed this pull request ?

**Comment by vj-abishek** [comment]
It is working fine when users go offline. Only added `navigator.onLine`, to check at the initial page load. After that, if the user goes offline it works fine.

**Comment by vj-abishek** [comment]
@jaideepghosh  Things I did in this pull request. 
- [x] If the internet is interrupted, the offline screen will be shown.
- [x] If the user entered without internet, offline screen will be shown(when PWA installed).

**Comment by jaideepghosh** [comment]
Great work @vj-abishek 🎉

**Pull request closed without merging**
