### PR TITLE
Fix typo in manifest

### PR DESCRIPTION
**Pull request by vj-abishek**
> Changed "Scope" => "scope"

@jaideepghosh  PWA installation not working due to this typo

### CODE REVIEW

**Comment by jaideepghosh** [comment]
That manifest is auto generated by CRA.
And FYI, the PWA feat is working pretty well.

**Comment by vj-abishek** [comment]
But still, the issue exists. You used "S", instead of "s". in your PWA. PWA not working due to that issue

**Comment by vj-abishek** [comment]
Installation prompt not working in mobile and desktop.

**Comment by vj-abishek** [comment]
@jaideepghosh  check manifest.json. In both development and master branch, there is a typo. Due to which PWA installation not working. Please reply.

**Comment by jaideepghosh** [comment]
As I mentioned  that the manifest is auto generated, So I don't see any need of manual change in that, till a cuatom requirement.

**Comment by vj-abishek** [comment]
Annotation 2020-10-04 130501


@jaideepghosh check this.

**Comment by vj-abishek** [comment]
@jaideepghosh  it is not a manual change, it is a type. After that change, the PWA installation will work. Trust me

**Comment by vj-abishek** [comment]
@jaideepghosh yes, CRA default is Scope. I'm sorry. But PWA prompt not working why?

**Comment by vj-abishek** [comment]
@jaideepghosh I think the scope needs to be `/react-covid19-stats` . Cause you are deploying to GitHub pages. What do you think?

**Comment by vj-abishek** [comment]
@jaideepghosh for you, PWA is working?

**Comment by jaideepghosh** [comment]
Yes

**Pull request closed without merging**
