### PR TITLE
Added LocalStorage to dark mode

### PR DESCRIPTION
**Pull request by romasinha**
The page stays in the selected mode even after getting refreshed.

### CODE REVIEW

**Comment by jaideepghosh** [comment]
Hey @romasinha 
Please resolve the conflicts.

**Comment by romasinha** [comment]
Hey @jaideepghosh Please review once.

**Comment by jaideepghosh** [comment]
Hey @romasinha 
Could you please have a look on the changes. Because I'm unable to run the application with your changes. Please find the issue screenshot in the attachment.
Screenshot 2020-10-03 at 4 05 00 PM

I'd suggest you to run the app locally, and test your changes. Once everything is fixed, then you can let us know by adding your comment in this thread.

**Comment by romasinha** [comment]
image

There should not be any problem. I have resolved all the conflicts. And the application is running without any issues.

**Comment by romasinha** [comment]
Hey @jaideepghosh please review once.

**Comment by romasinha** [comment]
@jaideepghosh Please review and merge accordingly.

**Comment by romasinha** [comment]
@jaideepghosh ?

**Comment by jaideepghosh** [comment]
@romasinha 
I'll review in sometime. Thanks.

**Comment by jaideepghosh** [comment]
Great work @romasinha 
Can you please fix the warnings also?
Screenshot 2020-10-05 at 4 47 23 PM

**Comment by romasinha** [comment]
Okay.

**Comment by romasinha** [comment]
@jaideepghosh Hey, I have fixed the warnings.

image

**Comment by romasinha** [comment]
Hey @jaideepghosh Can you please go ahead and merge the PR?

**Comment by jaideepghosh** [comment]
Hey @romasinha 
Thanks for your contribution. Please create MR to `development` branch.

**Comment by romasinha** [comment]
Okay, I will do it.

**Comment by romasinha** [comment]
I haven't used Gitlab earlier or created a merge request. What should I do now?

**Pull request closed without merging**
